/* #define \
    _SPO_XXXX : Conf    User configurable but defaults should be just fine
                [_Safe] Tells the related functions to perform assertions preventing erroneous behavior, more often then not caused by user input (1:safe)
                Const   A constant, don't touch
                Data    A value generated by the translator, you should probably don't touch either
                Inc     An include (.inc/.sp) file
   #assert \
    Assertions are tests for Conf defines preventing erroneous values to be used.
 */